version: "3.8"

services:
  # .NetApi
  web_api:
    image: docker.io/library/gamesapi:latest
    container_name: dotnet_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      - psql_db
    networks:
      - custom_container_network

    # postgres database
  psql_db:
    image: postgres:17-alpine
    restart: always
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - gamesdbdata:/var/lib/postgresql/data
    networks:
      - custom_container_network

networks:
  custom_container_network:
    driver: bridge

volumes:
  gamesdbdata:
